name: app24
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^4.0.0
  latlong2: ^0.8.1
  geolocator: ^13.0.2
  firebase_core: ^3.9.0
  firebase_auth: ^5.3.4

  http: ^0.13.5
  cupertino_icons: ^1.0.8
  intl: ^0.18.0
  csv: ^6.0.0
  path_provider: ^2.0.14
  google_maps_flutter: ^2.1.1
  url_launcher: ^6.1.5
  geocoding: ^3.0.0
  geocoding_platform_interface: ^3.2.0

  font_awesome_flutter: ^10.0.0
  flutter_sound: ^9.0.0
  permission_handler: ^11.3.1
  record: ^5.0.0
  speech_to_text: ^7.0.0
  shared_preferences: ^2.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/womens_2.png
    - assets/logo.jpg
    - assets/logo_remov.jpg
    - assets/cam.jpeg
    - .env
